apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-cluster-secret-stores
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vasek18/av-gitops.git
    targetRevision: main
    path: platform/external-secrets/cluster-secret-stores
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
