apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-pg/cloudnative-pg.git
    targetRevision: v1.30.0
    path: config/crd/bases
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Prune=false
