apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-hours-backend-secret
  namespace: my-hours
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: my-hours-backend-secret
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: my-hours
        property: session-secret
