apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-hours
  namespace: my-hours
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: my_hours
      owner: my_hours
