apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-hours
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Vasek18/my-hours-go.git
      targetRevision: main
      path: charts/my-hours
      helm:
        values: |
          backend:
            env:
              appUrl: https://my-hours.65.109.223.208.sslip.io
              redisAddr: my-hours:6379
            databaseSecretName: my-hours-app
            databaseSecretKey: uri
            sessionSecretName: my-hours-backend-secret
    - repoURL: https://github.com/Vasek18/av-gitops.git
      targetRevision: main
      path: workloads/my-hours
  destination:
    server: https://kubernetes.default.svc
    namespace: my-hours
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
